sudo: required
services:
  - docker

before_install:
  - docker login -u=_ -p=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t $DOCKER_TAG -f Dockerfile.dev .
  - docker run -e CI=true $DOCKER_TAG npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    docker tag $DOCKER_TAG registry.heroku.com/$HEROKU_APP_NAME/web
    docker push registry.heroku.com/$HEROKU_APP_NAME/web
    curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation -d '{"updates": [{"type": "web","docker_image": "$WEB_DOCKER_IMAGE_ID"},]}' -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
  on:
    branch: master
