sudo: required
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login --username=_ --password=$HEROKU-API-KEY registry.heroku.com

script:
  - docker build -t $DOCKER-TAG -f Dockerfile.dev .
  - docker run -e CI=true $DOCKER-TAG npm run test

deploy:
  provider: script
  script:
    #Push a Heroku container
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master
